@url_dev=http://localhost:3000/v1/api
@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMDI3MGUzNS1lYTFhLTRkMGItYTE0My1hZjg5ODgxMDE0YzIiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcxMTU0MDgxNywiZXhwIjoxNzExNzEzNjE3fQ.OyhAga_kPth32JlljTkSII9ZFjm35syN0qNDOsfdFRw1N97YmbHkZwzXDB7WybH5p4ULQy0qrRyCklYiy2i8Tghr_NoEbbpGBNGTObZtXeR08jg4xZUpdC_CdzLShMpSMziFu_4NV79pyJdWQc6_CKgFWm1vu81Y3MU-sRCKZNX6abyiKxqFUWKP1tUyTOUyE1109R9H3lNi_tZLdGrb0wa_-qtyp1v3aETgC2GLO4w3aer2P9buXwQlvPYRsmkSB51BFnUijgD4bNcmMAi7tOS1trxRB3lpQmqDBF9ZrnF5m2F6SFMsWfCPHNobG76mDVcrCpzk82OdUI-6ezCWaQ
@client-id=00270e35-ea1a-4d0b-a143-af89881014c2

### Create Discount
POST {{url_dev}}/discount/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
  "discount_name": "iPhone Sale" ,
  "discount_description": "Black Friday",
  "discount_type": "other",
  "discount_value": 10,
  "discount_code": "SALE",
  "discount_start_date": "2024-03-27 10:00:00",
  "discount_end_date": "2025-03-27 10:00:00",
  "discount_max_uses": 10,
  "usesCount": 0,
  "usersUsed" : 0,
  "discount_max_uses_per_user": 1000,
  "discount_min_order_value": 10,
  "discount_shop_id": "00270e35-ea1a-4d0b-a143-af89881014c2",
  "discount_is_active": true,
  "discount_applies_to": "all"
}