@url_dev=http://localhost:3000/v1/api
@client-id=697e7ef2-8e07-49a3-9e38-8cddd7f19fdb
@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTdlN2VmMi04ZTA3LTQ5YTMtOWUzOC04Y2RkZDdmMTlmZGIiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcxMTQ2Mzk2MiwiZXhwIjoxNzExNjM2NzYyfQ.GEFkfARFh6H9Ome5hR4Wmq75A0UVXcAj4WrWwo4X-p6I6UJ3_tmpMSpgVmg-yJJFIZAUUjGGlU-pyZgsXYuXsLfhJGSaZxU-v56jHO9oy2DRGBwKrpnbo8l75znwXdj0idlDL-gL7eA0Km3eFyVySsFS9AnFsurLY1BozPfPzwOtEVLw3BXSBwL1TmuWh7X1d0CwWChx634vQWONdXtS985-fEa-SLiaQ1Pbw3DlXzSDXsKDjbSOj3kgRdKeTdrBU75x_Y6ddiDd6Qca6kH2wgpgwq2M1fmOac0xGV2Wc7zlFvU0uv3_ZzQuW6fOIGSV7IixjyBA024E9HqX9dZgVA

### CREATE Electronic
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
  "product_type": "Electronics",
  "product_name": "Smart Air Purifier with True HEPA Filter, removes 99.97% of airborne allergens",
  "product_thumbs": "Image",
  "product_description": "Enjoy cleaner air with this smart air purifier",
  "product_price": 150,
  "product_quantity": 50,
  "product_variations": [1, 2]
}


### CREATE Clothes
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
    "product_type": "Clothes",
    "product_name": "Shirt",
    "product_thumbs": "Image",
    "product_description": "Expensive",
    "product_price": 100,
    "product_quantity": 100,
    "product_variations": [1, 4]
}


### CREATE Houseware
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
    "product_type": "Houseware",
    "product_name": "Vacum",
    "product_thumbs": "Image",
    "product_description": "Expensive",
    "product_price": 100,
    "product_quantity": 100,
    "product_variations": [1, 4]
}

### GET all public product
GET {{url_dev}}/product  HTTP/1.1
x-api-key: xxx

### GET public product by search box
GET {{url_dev}}/product/search/remove  HTTP/1.1
x-api-key: xxx

### GET All draft product 
GET {{url_dev}}/product/get_draft  HTTP/1.1
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

### GET Published product 
GET {{url_dev}}/product/get_published  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}


### POST Publish product 
PATCH  {{url_dev}}/product/publishProduct  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
    "product_id": "42641fb0-b7bb-4a9f-89a7-e3f449cffd51"
}

### POST Unpublish product 
PATCH  {{url_dev}}/product/unPublishProduct  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
    "product_id": "78afe790-05b8-4b75-970d-98825fc99344"
}

### POST Modify product 
PATCH  {{url_dev}}/product/modifyProduct  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
    "product_id": "42641fb0-b7bb-4a9f-89a7-e3f449cffd51",
    "product_name": "Smart Air Purifier with True HEPA Filter, removes 99.97% of airborne allergens",
    "product_thumb": "Image",
    "product_description": "Enjoy cleaner air with this smart air purifier",
    "product_price": 150
}
