version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: local_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: thuan
      POSTGRES_PASSWORD: thuan286
      POSTGRES_LOG_LEVEL: all 
    ports:
      - "5432:5432"
    volumes:
      - ./database/user/user.init.sql:/docker-entrypoint-initdb.d/01.user.init.sql
      - ./database/product/product.init.sql:/docker-entrypoint-initdb.d/02.product.init.sql
      - ./database/product/category/category.init.sql:/docker-entrypoint-initdb.d/03.category.init.sql
      - ./database/migrate:/usr/migrate

#   bun:
#     container_name: bun
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#       args:
#         - PORT=${SERVER_PORT_DEV}
#     ports:
#       - 3000:${SERVER_PORT_DEV}
#       - 6499:6499
#     env_file:
#       - .env
#     volumes:
#       - ./:/usr/local/bun
#       - ignore:/usr/local/bun/node_modules
# volumes:
#   ignore:
