@url_dev=http://localhost:3000/v1/api
@client-id=de0ddf07-9873-44d0-9695-7cc8394ac1bb
@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkZTBkZGYwNy05ODczLTQ0ZDAtOTY5NS03Y2M4Mzk0YWMxYmIiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcxMTI2ODc5NSwiZXhwIjoxNzExNDQxNTk1fQ.ABeRBkiFr__-3AeiiAuyIuQ9my3SaFFxAslBybyx2ShC9yDcKyGt_iqv3LTjVjoPjRQBHSvjOulg60MrfkMtZNiajUB04cQhxtdaG5nBlr3V6cajf4E3y6wsVhtzNNlJqKOaeng5Tq3EcjWvwdFZyCZdJhgCUyW2SA1ryWPDOjTiM-9UKiGLFHmbsYuiPhqxs9a9jQg23me94kLBBFLTlUgpRNpOHg7hvnvZ_izZknS69IsjoWGIj1SswzB323tb47QzqNBBR3bezfhzGxc8NzNfQH06T1gjtnAsWjwh5yBkcag6xvCXD9niMRAoJ9HDPCCTcwAUNg2gAuzlfUN23w

### CREATE Electronic
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
  "product_type": "Electronics",
  "product_name": "Smart Air Purifier with True HEPA Filter, removes 99.97% of airborne allergens",
  "product_thumbs": "Image",
  "product_description": "Enjoy cleaner air with this smart air purifier",
  "product_price": 150,
  "product_quantity": 50,
  "product_variations": [1, 2]
}


### CREATE Clothes
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
    "product_type": "Clothes",
    "product_name": "Shirt",
    "product_thumbs": "Image",
    "product_description": "Expensive",
    "product_price": 100,
    "product_quantity": 100,
    "product_variations": [1, 4]
}

### CREATE Houseware
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
    "product_type": "Houseware",
    "product_name": "Vacum",
    "product_thumbs": "Image",
    "product_description": "Expensive",
    "product_price": 100,
    "product_quantity": 100,
    "product_variations": [1, 4]
}

### GET all public product
GET {{url_dev}}/product  HTTP/1.1
x-api-key: xxx

### GET public product by search box
GET {{url_dev}}/product/search/remove  HTTP/1.1
x-api-key: xxx

### GET All draft product 
GET {{url_dev}}/product/get_draft  HTTP/1.1
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

### GET Published product 
GET {{url_dev}}/product/get_published  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}


### POST Publish product 
PATCH  {{url_dev}}/product/publishProduct  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
    "product_id": "78afe790-05b8-4b75-970d-98825fc99344"
}

### POST Unpublish product 
PATCH  {{url_dev}}/product/unPublishProduct  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
    "product_id": "78afe790-05b8-4b75-970d-98825fc99344"
}

### POST Modify product 
PATCH  {{url_dev}}/product/modifyProduct  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
    "product_id": "78afe790-05b8-4b75-970d-98825fc99344",
    "product_name": "Smart Air Purifier with True HEPA Filter, removes 99.97% of airborne allergens",
    "product_thumb": "Image",
    "product_description": "Enjoy cleaner air with this smart air purifier",
    "product_price": 150
}
