@url_dev=http://localhost:3000/v1/api
@client-id=de0ddf07-9873-44d0-9695-7cc8394ac1bb
@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkZTBkZGYwNy05ODczLTQ0ZDAtOTY5NS03Y2M4Mzk0YWMxYmIiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcxMTE3Nzk3MiwiZXhwIjoxNzExMzUwNzcyfQ.zEV5xvq8mvDfF7Bte8kKgWQuyhlDI1SwPDwXhvSCUC6ST1c88FUT4KvTv-7j01OIFhiRnTQfuoEp2vcbSKTYrEz7x2wqL2RiSrjaSjGxrrCSVcld150nTKlNy9-BhHAGVXwLIx9Ir8reSzKdhccvHAFEoN0wlgWs9omZ23BUUp3Fzu7pmrPxSC8ZLvEPo0VmCoI-XoLVxHsQ2HqGESM3nmXw0RXxKNJvAGgsTHYxwbcEggD8y0r8NfSGTFiVMQKF1irJXKKkdbp834r81PgqPmqU1ot6aYCCx_xoyvqFQd9M9c_ICdMQ3g4LUchWrrJZzHgTQ4ptCju8gro-6qGuwQ

### CREATE Electronic
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
  "product_type": "Electronics",
  "product_name": "Smart Air Purifier with True HEPA Filter, removes 99.97% of airborne allergens",
  "product_thumbs": "Image",
  "product_description": "Enjoy cleaner air with this smart air purifier",
  "product_price": 150,
  "product_quantity": 50,
  "product_variations": [1, 2]
}


### CREATE Clothes
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
    "product_type": "Clothes",
    "product_name": "Shirt",
    "product_thumbs": "Image",
    "product_description": "Expensive",
    "product_price": 100,
    "product_quantity": 100,
    "product_variations": [1, 4]
}

### CREATE Houseware
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
    "product_type": "Houseware",
    "product_name": "Vacum",
    "product_thumbs": "Image",
    "product_description": "Expensive",
    "product_price": 100,
    "product_quantity": 100,
    "product_variations": [1, 4]
}

### GET all public product
GET {{url_dev}}/product  HTTP/1.1
x-api-key: xxx

### GET public product by search box
GET {{url_dev}}/product/search/remove  HTTP/1.1
x-api-key: xxx

### GET All draft product 
GET {{url_dev}}/product/get_draft  HTTP/1.1
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

### GET Published product 
GET {{url_dev}}/product/get_published  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}


### POST Publish product 
POST {{url_dev}}/product/publishProduct  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
    "product_id": "78afe790-05b8-4b75-970d-98825fc99344"
}

### POST Modify product 
POST {{url_dev}}/product/modifyProduct  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: {{client-id}}
Authorization: Bearer {{token}}

{
    "product_id": "78afe790-05b8-4b75-970d-98825fc99344",
    "product_name": "Smart Air Purifier with True HEPA Filter, removes 99.97% of airborne allergens",
    "product_thumb": "Image",
    "product_description": "Enjoy cleaner air with this smart air purifier",
    "product_price": 150
}
