@url_dev=http://localhost:3000/v1/api
@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzZGJlNWQ5Ny00ZmZjLTRhM2UtYTM4Ny04YmQ1OTVmNDllNTMiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcxMTE1NzkyNywiZXhwIjoxNzExMzMwNzI3fQ.rRvrNDsERcglcBZ14m5rTeLmbkXi5Q_yjYTelY8hNocQlCuCqv2WkvYtuh5036fhJNKTLqvOHqSs1MRzcUGLzOuEOFfmciQ-hLdeBnHIBEY-b6S6a-IfvO_63p3BPmQ4N4ufGjXukBDQwspqqlESzEaQ4B2LBmTp6ZnaQz2mGXxeY9_CRUmTWq06f_MMZRt6HyKGKw5HnEGMATjadV_NsNLuaIi9QquqZ0RtwPbTJi4WYhVRdBZm1PUN5i-YMbAnWxz4ITQTLwJtsTxuMwDel0Ch_W7V9537MXnZN9xC-SzFICLOGxBQ9XFp4GP87W2kQx4yH0bSBBUHEYdowmkyCQ

@refresh=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzZGJlNWQ5Ny00ZmZjLTRhM2UtYTM4Ny04YmQ1OTVmNDllNTMiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcxMTE2MTg4NywiZXhwIjoxNzExNzY2Njg3fQ.T7qmtHeoutPqvUu_GYTIpit4L_6UlY34pGs7VEJlsVml04dXxNL2GYY45xXyubaH2MCGq2YOVIk_-i8rsyowh5BEY8iRh4zTmN57Yqg20Ku7Q4sH523FZx-Wd51bLdvS44gr-WlGu3q9sj64Yq1wTce1Q2x8NJdMyuzKEgS7yonQPXOXIhk5PfwSz1cu5LnsSHeYmGSp5Zx2SxW9k8NZID_4v_gnpy2SZ_SHWXfGerDJeZ0s3wRsW7OZTPZviLVk42Ui_dFAZYLgeXW6PMmGbJj82ZxQcOW4nD5YJLIQK56_MhBgOyhCbrswFOHjs5373a_DzAzGDy_sM7LEZNr7IA

###test
GET http://localhost:3000

### root
GET {{url_dev}}
x-api-key: xxx

### Signup
POST {{url_dev}}/shop/signup  HTTP/1.1
Content-Type: application/json
x-api-key: xxx

{
    "email": "thuan@gmail.com",
    "name": "pham",
    "username": "pvt",
    "password": "1"
}

### Login
POST {{url_dev}}/shop/login  HTTP/1.1
Content-Type: application/json
x-api-key: xxx

{
    "email": "thuan@gmail.com",
    "password": "1"
}

### Logout
POST {{url_dev}}/shop/logout  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: d959b636-5afe-4eb9-a592-5288463e3a55
Authorization: Bearer {{token}}

### Refresh
POST {{url_dev}}/shop/refresh  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: 3dbe5d97-4ffc-4a3e-a387-8bd595f49e53
Authorization: Refresh {{refresh}}