@url_dev=http://localhost:3000/v1/api

### root
GET {{url_dev}}
x-api-key: xxx

### Signup
POST {{url_dev}}/shop/signup  HTTP/1.1
Content-Type: application/json
x-api-key: xxx

{
    "email": "thuan@gmail.com",
    "name": "pham",
    "username": "pvt",
    "password": "1"
}

### Login
POST {{url_dev}}/shop/login  HTTP/1.1
Content-Type: application/json
x-api-key: xxx

{
    "email": "thuan@gmail.com",
    "password": "1"
}

### Logout
POST {{url_dev}}/shop/logout  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: fb4eadea-0b39-414c-a122-c5e205b76bbf
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmYjRlYWRlYS0wYjM5LTQxNGMtYTEyMi1jNWUyMDViNzZiYmYiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcwNzYyNzI3MywiZXhwIjoxNzA3ODAwMDczfQ.XrmhZvdlNolXB3tMPKrXC6HaBoGE0cE7CWyRZ3p95mCGborHZ2eBnFmP9jkm65mxZHZfbaapIDRUIRx4VXHxXThH0jzqvjJii-cljpkGou3kwW5RtcM_5orZ6adsFn4Cc3r_t2KlcJQ3Kdh3lmAjZITDKzeNwGsppw2PpiSuHuGDPG_nc_sH6DnQUX17QDtFI5d4E07FjQB7pXfEdu8Vd9wHJd53kLCBpuSidYrpQwSfc4oMprrhgoB0QTkxiRtCXyXjXZttPeMh4W_2NJPVgmxInxPyW3n78ibvT_4w4YTAySKOgKcjMBny7vKMGGeVt62pa4tPdP9wVIIazzcWhA
### Refresh
POST {{url_dev}}/shop/refresh  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: 1
Authorization: Refresh eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGh1YW4iLCJpYXQiOjE3MDY2MzQwOTIsImV4cCI6MTcwNzIzODg5Mn0.ImXNLxafbRsC-WpA1gHhpIgbIRc_siwwHIb-ZA3dseenHOYPBNDfnJJmRQC6TQz8GgyX0-TcSQ8wBHvoZ06NkJn6xRJ-wGimlLNg_REMvF-l-rNQ0uUEjDOYqHHEL5prN-yc33w3vaR28aXnBl7S7KTSH2hjlJiYCN4GJRwBFMZKxNPXLWs9fs7XmAoM8U-vyYR0QusijIlVSjqUMT_WtgGaRlCnU7Di3bJjYry4mpAEpHr2OU1WNewg4bh08mb3TTHvbZFO4C3tRSnUPqjFpQSExpU9GeL8bF_4Ny5ZJ_2J5T_O7VYqaC0e4I29Vo3ofO6gO5CRS7QeUOvvyVuAYg