@url_dev=http://localhost:3000/v1/api

### root
GET {{url_dev}}
x-api-key: xxx

### Signup
POST {{url_dev}}/shop/signup  HTTP/1.1
Content-Type: application/json
x-api-key: xxx

{
    "email": "thuan@gmail.com",
    "name": "pham",
    "username": "pvt",
    "password": "1"
}

### Login
POST {{url_dev}}/shop/login  HTTP/1.1
Content-Type: application/json
x-api-key: xxx

{
    "email": "thuan@gmail.com",
    "password": "1"
}

### Logout
POST {{url_dev}}/shop/logout  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: d959b636-5afe-4eb9-a592-5288463e3a55
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkOTU5YjYzNi01YWZlLTRlYjktYTU5Mi01Mjg4NDYzZTNhNTUiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcwNzY0NDI2NCwiZXhwIjoxNzA3ODE3MDY0fQ.bBxUKCaAo_9BIZWKxVGhd1F5OpZ9_0ny6E6rEi__p7p-Eld_6pLYySOHgV4d2NIBbnmlmlh7pccdeUEq9yvvsOCnQM57uh-60G2Rv92i7If9hxBYJU13FTueA4_hnmRWe2N-NjD_oug9sIWsxp_Y-PYeFg1s6XoQVPbb8PRECY8Ibx-YNJHF2K4LbN69yO5SUdL6moOd5yg8xpc-iSpjQsyo4Q0R4nTEJvjdRr92dlxoL_CaWSOsxc8veOEk51dLqX8jPxJ3fhji1FPHVV6G-nYGlPjKJAVv1osROcwcPFftQJxmDQJ6nIQR3VHTdFbhnhVdoiVPbIYvwhrRj0JXyA
### Refresh
POST {{url_dev}}/shop/refresh  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: 1
Authorization: Refresh eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGh1YW4iLCJpYXQiOjE3MDY2MzQwOTIsImV4cCI6MTcwNzIzODg5Mn0.ImXNLxafbRsC-WpA1gHhpIgbIRc_siwwHIb-ZA3dseenHOYPBNDfnJJmRQC6TQz8GgyX0-TcSQ8wBHvoZ06NkJn6xRJ-wGimlLNg_REMvF-l-rNQ0uUEjDOYqHHEL5prN-yc33w3vaR28aXnBl7S7KTSH2hjlJiYCN4GJRwBFMZKxNPXLWs9fs7XmAoM8U-vyYR0QusijIlVSjqUMT_WtgGaRlCnU7Di3bJjYry4mpAEpHr2OU1WNewg4bh08mb3TTHvbZFO4C3tRSnUPqjFpQSExpU9GeL8bF_4Ny5ZJ_2J5T_O7VYqaC0e4I29Vo3ofO6gO5CRS7QeUOvvyVuAYg