@url_dev=http://localhost:3000/v1/api

### CREATE Electronic
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: d959b636-5afe-4eb9-a592-5288463e3a55
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkOTU5YjYzNi01YWZlLTRlYjktYTU5Mi01Mjg4NDYzZTNhNTUiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcwNzYyNzUxNSwiZXhwIjoxNzA3ODAwMzE1fQ.hTs7IIhrdEPwmAkFmRhJIEhjCL6ppn7nIHMIOSJohMvnO6kH80HiApz6CjekJGFHg2AHfXtvGPcNT9OQ5Kp7cFFhV8427vTw3zNFNsCQob-i_Vo8wK-J86zVa47l4ED8QmELrTIvW_yXnl2aIaoH28y2fQQfCUI6kqYG4GW79TpaRnUt9z7hq6ppm8QgPOCOoWY6FgZd2tEfYSgKSPqF5WhlDD2m-MkZ7HhE35tH4om0RT4OA6g0EuHR54XnsU78IuNXDEBddDEf84FPWlPa7nEItLb1_rpEI465I_mQQbFMEOT3oapvog--svUDWJ6QmmAhLm-1Oslq_1TMCprhbQ

{
    "product_type": "Electronics",
    "product_name": "IPhone",
    "product_thumbs": "Image",
    "product_description": "Expensive",
    "product_price": 100,
    "product_quantity": 100,
    "product_attribute": {
        "brand": "Apple",
        "color": "Black"
    }
}

### CREATE Clothes
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: d959b636-5afe-4eb9-a592-5288463e3a55
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkOTU5YjYzNi01YWZlLTRlYjktYTU5Mi01Mjg4NDYzZTNhNTUiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcwNzYyNzUxNSwiZXhwIjoxNzA3ODAwMzE1fQ.hTs7IIhrdEPwmAkFmRhJIEhjCL6ppn7nIHMIOSJohMvnO6kH80HiApz6CjekJGFHg2AHfXtvGPcNT9OQ5Kp7cFFhV8427vTw3zNFNsCQob-i_Vo8wK-J86zVa47l4ED8QmELrTIvW_yXnl2aIaoH28y2fQQfCUI6kqYG4GW79TpaRnUt9z7hq6ppm8QgPOCOoWY6FgZd2tEfYSgKSPqF5WhlDD2m-MkZ7HhE35tH4om0RT4OA6g0EuHR54XnsU78IuNXDEBddDEf84FPWlPa7nEItLb1_rpEI465I_mQQbFMEOT3oapvog--svUDWJ6QmmAhLm-1Oslq_1TMCprhbQ

{
    "product_type": "Clothes",
    "product_name": "Shirt",
    "product_thumbs": "Image",
    "product_description": "Expensive",
    "product_price": 100,
    "product_quantity": 100,
    "product_attribute": {
        "brand": "Apple",
        "size": 10
    }
}

### CREATE Houseware
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: d959b636-5afe-4eb9-a592-5288463e3a55
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkOTU5YjYzNi01YWZlLTRlYjktYTU5Mi01Mjg4NDYzZTNhNTUiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcwNzYyNzUxNSwiZXhwIjoxNzA3ODAwMzE1fQ.hTs7IIhrdEPwmAkFmRhJIEhjCL6ppn7nIHMIOSJohMvnO6kH80HiApz6CjekJGFHg2AHfXtvGPcNT9OQ5Kp7cFFhV8427vTw3zNFNsCQob-i_Vo8wK-J86zVa47l4ED8QmELrTIvW_yXnl2aIaoH28y2fQQfCUI6kqYG4GW79TpaRnUt9z7hq6ppm8QgPOCOoWY6FgZd2tEfYSgKSPqF5WhlDD2m-MkZ7HhE35tH4om0RT4OA6g0EuHR54XnsU78IuNXDEBddDEf84FPWlPa7nEItLb1_rpEI465I_mQQbFMEOT3oapvog--svUDWJ6QmmAhLm-1Oslq_1TMCprhbQ

{
    "product_type": "Houseware",
    "product_name": "Vacum",
    "product_thumbs": "Image",
    "product_description": "Expensive",
    "product_price": 100,
    "product_quantity": 100,
    "product_attribute": {
        "brand": "Apple",
        "color": "Red"
    }
}
