@url_dev=http://localhost:3000/v1/api

### CREATE Electronic
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: ee7d979e-7c31-4aa4-b9fc-1822137ddce5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlZTdkOTc5ZS03YzMxLTRhYTQtYjlmYy0xODIyMTM3ZGRjZTUiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcwODg2NjQzOSwiZXhwIjoxNzA5MDM5MjM5fQ.ePn6gaMfXfrGpwi9tetOiihQIbXSEe7pnaA7ebIH7QhrWFaV9NyFgXTbdhUSNoboZ-MMCp1K7HsnwbGq1B9gw70EyIil5YEixuowUPv2xRqyy4UuJuHlPrq9IeQOiKtGY4wnsQmJZYItcgVkptL9Ni-Mmv4Dhj34JTrRRne_EhOnNA4wooOc_F72jdU9yC7Pnoy4Bzqhg03CthvjFJUyhJzS0j_3173AbDLWc6MnaIN75c6BAEIT8JGGqK8xqzc19_Y75HtAAkvIrZqFcy7XFulpvhSd-Vpz5cvhCU_3f3EbnY9ujF-XE99e79Tjr81EQWwYkUfd3HURjC0p6A4emA

{
    "product_type": "Electronics",
    "product_name": "IPhone",
    "product_thumbs": "Image",
    "product_description": "Expensive",
    "product_price": 100,
    "product_quantity": 100,
    "product_variations": [1, 4]
}

### CREATE Clothes
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: ee7d979e-7c31-4aa4-b9fc-1822137ddce5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlZTdkOTc5ZS03YzMxLTRhYTQtYjlmYy0xODIyMTM3ZGRjZTUiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcwODg2NjQzOSwiZXhwIjoxNzA5MDM5MjM5fQ.ePn6gaMfXfrGpwi9tetOiihQIbXSEe7pnaA7ebIH7QhrWFaV9NyFgXTbdhUSNoboZ-MMCp1K7HsnwbGq1B9gw70EyIil5YEixuowUPv2xRqyy4UuJuHlPrq9IeQOiKtGY4wnsQmJZYItcgVkptL9Ni-Mmv4Dhj34JTrRRne_EhOnNA4wooOc_F72jdU9yC7Pnoy4Bzqhg03CthvjFJUyhJzS0j_3173AbDLWc6MnaIN75c6BAEIT8JGGqK8xqzc19_Y75HtAAkvIrZqFcy7XFulpvhSd-Vpz5cvhCU_3f3EbnY9ujF-XE99e79Tjr81EQWwYkUfd3HURjC0p6A4emA

{
    "product_type": "Clothes",
    "product_name": "Shirt",
    "product_thumbs": "Image",
    "product_description": "Expensive",
    "product_price": 100,
    "product_quantity": 100,
    "product_variations": [1, 4]
}

### CREATE Houseware
POST {{url_dev}}/product/create  HTTP/1.1
Content-Type: application/json
x-api-key: xxx
x-client-id: ee7d979e-7c31-4aa4-b9fc-1822137ddce5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlZTdkOTc5ZS03YzMxLTRhYTQtYjlmYy0xODIyMTM3ZGRjZTUiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcwODg2NjQzOSwiZXhwIjoxNzA5MDM5MjM5fQ.ePn6gaMfXfrGpwi9tetOiihQIbXSEe7pnaA7ebIH7QhrWFaV9NyFgXTbdhUSNoboZ-MMCp1K7HsnwbGq1B9gw70EyIil5YEixuowUPv2xRqyy4UuJuHlPrq9IeQOiKtGY4wnsQmJZYItcgVkptL9Ni-Mmv4Dhj34JTrRRne_EhOnNA4wooOc_F72jdU9yC7Pnoy4Bzqhg03CthvjFJUyhJzS0j_3173AbDLWc6MnaIN75c6BAEIT8JGGqK8xqzc19_Y75HtAAkvIrZqFcy7XFulpvhSd-Vpz5cvhCU_3f3EbnY9ujF-XE99e79Tjr81EQWwYkUfd3HURjC0p6A4emA

{
    "product_type": "Houseware",
    "product_name": "Vacum",
    "product_thumbs": "Image",
    "product_description": "Expensive",
    "product_price": 100,
    "product_quantity": 100,
    "product_variations": [1, 4]
}

### GET All draft product 
GET {{url_dev}}/product/get_draft  HTTP/1.1
x-api-key: xxx
x-client-id: ee7d979e-7c31-4aa4-b9fc-1822137ddce5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlZTdkOTc5ZS03YzMxLTRhYTQtYjlmYy0xODIyMTM3ZGRjZTUiLCJlbWFpbCI6InRodWFuQGdtYWlsLmNvbSIsImlhdCI6MTcwODg2NjQzOSwiZXhwIjoxNzA5MDM5MjM5fQ.ePn6gaMfXfrGpwi9tetOiihQIbXSEe7pnaA7ebIH7QhrWFaV9NyFgXTbdhUSNoboZ-MMCp1K7HsnwbGq1B9gw70EyIil5YEixuowUPv2xRqyy4UuJuHlPrq9IeQOiKtGY4wnsQmJZYItcgVkptL9Ni-Mmv4Dhj34JTrRRne_EhOnNA4wooOc_F72jdU9yC7Pnoy4Bzqhg03CthvjFJUyhJzS0j_3173AbDLWc6MnaIN75c6BAEIT8JGGqK8xqzc19_Y75HtAAkvIrZqFcy7XFulpvhSd-Vpz5cvhCU_3f3EbnY9ujF-XE99e79Tjr81EQWwYkUfd3HURjC0p6A4emA